import type { EventDefinition } from '../types';

export const DECATHLON_EVENTS: EventDefinition[] = [
  {
    id: 'dec_100m',
    name: '100m',
    type: 'track',
    measurementUnit: 'seconds',
    higherIsBetter: false,
    scoringConstants: { A: 25.4347, B: 18.0, C: 1.81 },
    competitionType: 'decathlon',
    order: 1,
  },
  {
    id: 'dec_long_jump',
    name: 'Long Jump',
    type: 'field',
    measurementUnit: 'meters',
    higherIsBetter: true,
    scoringConstants: { A: 0.14354, B: 220, C: 1.4 },
    competitionType: 'decathlon',
    order: 2,
  },
  {
    id: 'dec_shot_put',
    name: 'Shot Put',
    type: 'field',
    measurementUnit: 'meters',
    higherIsBetter: true,
    scoringConstants: { A: 51.39, B: 1.5, C: 1.05 },
    competitionType: 'decathlon',
    order: 3,
  },
  {
    id: 'dec_high_jump',
    name: 'High Jump',
    type: 'field',
    measurementUnit: 'meters',
    higherIsBetter: true,
    scoringConstants: { A: 0.8465, B: 75.0, C: 1.42 },
    competitionType: 'decathlon',
    order: 4,
  },
  {
    id: 'dec_400m',
    name: '400m',
    type: 'track',
    measurementUnit: 'seconds',
    higherIsBetter: false,
    scoringConstants: { A: 1.53775, B: 82.0, C: 1.81 },
    competitionType: 'decathlon',
    order: 5,
  },
  {
    id: 'dec_110m_hurdles',
    name: '110m Hurdles',
    type: 'track',
    measurementUnit: 'seconds',
    higherIsBetter: false,
    scoringConstants: { A: 5.74352, B: 28.5, C: 1.92 },
    competitionType: 'decathlon',
    order: 6,
  },
  {
    id: 'dec_discus',
    name: 'Discus Throw',
    type: 'field',
    measurementUnit: 'meters',
    higherIsBetter: true,
    scoringConstants: { A: 12.91, B: 4.0, C: 1.1 },
    competitionType: 'decathlon',
    order: 7,
  },
  {
    id: 'dec_pole_vault',
    name: 'Pole Vault',
    type: 'field',
    measurementUnit: 'meters',
    higherIsBetter: true,
    scoringConstants: { A: 0.2797, B: 100, C: 1.35 },
    competitionType: 'decathlon',
    order: 8,
  },
  {
    id: 'dec_javelin',
    name: 'Javelin Throw',
    type: 'field',
    measurementUnit: 'meters',
    higherIsBetter: true,
    scoringConstants: { A: 10.14, B: 7.0, C: 1.08 },
    competitionType: 'decathlon',
    order: 9,
  },
  {
    id: 'dec_1500m',
    name: '1500m',
    type: 'track',
    measurementUnit: 'seconds',
    higherIsBetter: false,
    scoringConstants: { A: 0.03768, B: 480.0, C: 1.85 },
    competitionType: 'decathlon',
    order: 10,
  },
];

export const HEPTATHLON_EVENTS: EventDefinition[] = [
  {
    id: 'hep_100m_hurdles',
    name: '100m Hurdles',
    type: 'track',
    measurementUnit: 'seconds',
    higherIsBetter: false,
    scoringConstants: { A: 9.23076, B: 26.7, C: 1.835 },
    competitionType: 'heptathlon',
    order: 1,
  },
  {
    id: 'hep_high_jump',
    name: 'High Jump',
    type: 'field',
    measurementUnit: 'meters',
    higherIsBetter: true,
    scoringConstants: { A: 1.84523, B: 75.0, C: 1.348 },
    competitionType: 'heptathlon',
    order: 2,
  },
  {
    id: 'hep_shot_put',
    name: 'Shot Put',
    type: 'field',
    measurementUnit: 'meters',
    higherIsBetter: true,
    scoringConstants: { A: 56.0211, B: 1.5, C: 1.05 },
    competitionType: 'heptathlon',
    order: 3,
  },
  {
    id: 'hep_200m',
    name: '200m',
    type: 'track',
    measurementUnit: 'seconds',
    higherIsBetter: false,
    scoringConstants: { A: 4.99087, B: 42.5, C: 1.81 },
    competitionType: 'heptathlon',
    order: 4,
  },
  {
    id: 'hep_long_jump',
    name: 'Long Jump',
    type: 'field',
    measurementUnit: 'meters',
    higherIsBetter: true,
    scoringConstants: { A: 0.188807, B: 210, C: 1.41 },
    competitionType: 'heptathlon',
    order: 5,
  },
  {
    id: 'hep_javelin',
    name: 'Javelin Throw',
    type: 'field',
    measurementUnit: 'meters',
    higherIsBetter: true,
    scoringConstants: { A: 15.9803, B: 3.8, C: 1.04 },
    competitionType: 'heptathlon',
    order: 6,
  },
  {
    id: 'hep_800m',
    name: '800m',
    type: 'track',
    measurementUnit: 'seconds',
    higherIsBetter: false,
    scoringConstants: { A: 0.11193, B: 254.0, C: 1.88 },
    competitionType: 'heptathlon',
    order: 7,
  },
];

export function getEventsForType(type: 'decathlon' | 'heptathlon'): EventDefinition[] {
  return type === 'decathlon' ? DECATHLON_EVENTS : HEPTATHLON_EVENTS;
}

export function getEventById(id: string): EventDefinition | undefined {
  return [...DECATHLON_EVENTS, ...HEPTATHLON_EVENTS].find((e) => e.id === id);
}
